

products = [
  {
    '_id': "1",
    'name': "Car20",
    'image': "src\assets\images\Drum1.png",
    'description': "Acool description goes here!",
    'brand': "My brand",
    'Category': "My category",
    'price': 45.56,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': "2",
    'name': "Car20",
    'image': "src\assets\images\Drum1.png",
    'description': "Acool description goes here!",
    'brand': "My brand",
    'Category': "My category",
    'price': 45.56,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
   {
    '_id': "3",
    'name': "Car20",
    'image': "src\assets\images\Drum1.png",
    'description': "Acool description goes here!",
    'brand': "My brand",
    'Category': "My category",
    'price': 45.56,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
   {
    '_id': "4",
    'name': "Car20",
    'image': "src\assets\images\Drum1.png",
    'description': "Acool description goes here!",
    'brand': "My brand",
    'Category': "My category",
    'price': 45.56,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': "5",
    'name': "Car20",
    'image': "src\assets\images\Drum1.png",
    'description': "Acool description goes here!",
    'brand': "My brand",
    'Category': "My category",
    'price': 45.56,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
   {
    '_id': "6",
    'name': "Car20",
    'image': "src\assets\images\Drum1.png",
    'description': "Acool description goes here!",
    'brand': "My brand",
    'Category': "My category",
    'price': 45.56,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
   {
    '_id': "7",
    'name': "Car20",
    'image': "src\assets\images\Drum1.png",
    'description': "Acool description goes here!",
    'brand': "My brand",
    'Category': "My category",
    'price': 45.56,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
];


